//独立COOKIE文件     ck在``里面填写，多账号换行

let qmydtokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgyMTYwNywiZXhwIjoyMDUzNjQyMTYwNywibmJmIjoxNjE0ODIxNjA3LCJqdGkiOiJMT2RsUjhybExHSHVLdUNxIiwic3ViIjoxMTYwODMsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.cw4Q-fScjYMFyFTeX6hNYZwYAqMZI2fhFxrxrOp_BEk
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgzMjIyMiwiZXhwIjoyMDUzNjQzMjIyMiwibmJmIjoxNjE0ODMyMjIyLCJqdGkiOiI3OWhjM2pTTzcwUGRFa0hLIiwic3ViIjoxMTYyODQsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.BUKcTKY-CKzcbvKxlEOBri0uYeav7iEBQahjHuj2GGM
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgzMjMxMiwiZXhwIjoyMDUzNjQzMjMxMiwibmJmIjoxNjE0ODMyMzEyLCJqdGkiOiJZSXBIVXkySDZmZGpaQmNwIiwic3ViIjoxMTYyODcsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.Yb_GGsWSAhHNP2_brvcJJi_bHnnLeTxPmOepaY2qVQo
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgzMjQ3MywiZXhwIjoyMDUzNjQzMjQ3MywibmJmIjoxNjE0ODMyNDczLCJqdGkiOiJJZzB0dElEdW1ibm5yMVJmIiwic3ViIjoxMTYyOTQsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.bxethVol44WUQTHWXCrwqYRnMyZX66jxsLu8NM5lHXE`








let qmydcookie = {

    qmydtokenVal: qmydtokenVal,

}

module.exports = qmydcookie